public_html/customer/controllers/ColourController.php
<?php

namespace customer\controllers;

use Yii;
use frontend\components\Controller;
use yii\filters\AccessControl;
use common\helpers\Utility;
use frontend\models\ClientRepresentativeForm;
use frontend\models\ClientRepresentativeListForm;
use common\models\aq\UserQuery;
use yii\data\Pagination;
use yii\web\Response;
use yii\widgets\ActiveForm;
use common\models\ar\User;
use yii\helpers\Url;
use common\models\aq\RalColourGroupQuery;
use yii\helpers\ArrayHelper;

class ColourController extends Controller {
    
   /* public function behaviors() {
        $actions = ['list', 'create', 'details', 'delete', 'edit'];
        
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $actions,
                'rules' => [
                    [
                        'actions' => $actions,
                        'allow' => Yii::$app->params['isClientRepresentativeManagementVisible'],
                        'roles' => [Utility::ROLE_SALESMAN],
                    ],
                ],
            ],
        ];
    }
    */
    public function actionRenderRalColourPicker() {
       $colours = RalColourGroupQuery::getAllColours();
       $groups = RalColourGroupQuery::getGroups();
       $colours = ArrayHelper::index($colours, null, 'groupSymbol');
       return $this->render('ralColourPicker', [
           'groups' => $groups,
           'colours' => $colours,
       ]);
       
    }
    
    public function actionGetModalContent() {
        $colours = RalColourGroupQuery::getAllColours();
        $groups = RalColourGroupQuery::getGroups();
        $colours = ArrayHelper::index($colours, null, 'groupSymbol');
        
        return $this->renderPartial('_ralColourPickerModalContent', [
            'groups' => $groups,
            'colours' => $colours,
        ]);
    }
    
    
}

public_html/customer/controllers/OrderController.php
<?php

namespace customer\controllers;

use Yii;
use frontend\components\Controller;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\data\Pagination;
use yii\web\Response;
use yii\web\BadRequestHttpException;
use yii\widgets\ActiveForm;
use common\models\aq\OrderQuery;
use common\models\ar\OrderStatusTranslation;
use common\models\ar\OrderStatus;
use common\models\ar\Order;
use customer\models\OrdersListForm;
use customer\models\OrderProductForm;
use customer\models\OrderCostForm;
use customer\models\OrderModel;
use frontend\models\OrderEmployeesForm;
use frontend\models\OrderHistoryForm;
use yii\helpers\ArrayHelper;
use common\models\aq\OrderHistoryQuery;
use common\helpers\Utility;
use common\models\aq\UserQuery;
use common\models\aq\UserOrderSalesmanQuery;
use common\models\aq\OrderStatusQuery;
use common\models\ar\Currency;
use common\models\ar\ProductTranslation;
use common\models\ar\User;
use common\models\ar\Entity;
use common\models\ar\Language;
use common\models\ar\OrderStatusTransition;
use common\helpers\StringHelper;
use common\models\aq\WarehouseProductQuery;
use common\alerts\OrderDeadlineAlertHandler;
use frontend\models\AlertForm;
use yii\mongodb\Query;
use common\models\aq\OrderTypeQuery;
use yii\filters\VerbFilter;
use common\models\aq\DocumentQuery;
use common\models\aq\OrderUserRepresentativeQuery;
use frontend\helpers\ModelLoaderHelper;
use common\documents\DocumentTypeUtility;
use common\models\aq\OrderTypeSetQuery;
use frontend\models\OrderTableForm;
use yii\helpers\Json;
use common\models\ar\OrderOfferedProductAttachment;
use common\models\ar\OfferedProduct;
use common\models\aq\OrderOfferedProductAttributeQuery;
use common\models\aq\ProductAttributeTypeQuery;
use customer\logic\ProductAttributeTypeLogic;
use common\models\ar\Company;
use common\models\aq\ShapeQuery;
use common\models\aq\ConstructionQuery;
use common\models\aq\MuntinQuery;
use common\models\ar\Product;
use common\models\ar\Shape;
use common\models\ar\OfferedProductTranslation;
use frontend\models\ArtificialProductAttributeForm;
use frontend\models\ProductAttributeForm;
use common\models\ar\RalColour;

class OrderController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'list', 'details', 'create', 'get-product-form', 'get-photo-form',
                    'get-document-form', 'get-employee-form', 'update', 'find', 'copy', 'edit', 'quick-update',
                    'get-user-representatives', 'delete', 'get-all-products-summary', 'get-custom-data-summary',
                    'get-custom-data-numeration', 'summary', 'get-color-and-shape'],
                'rules' => [
                    [
                        'actions' => ['index', 'list', 'details', 'create', 'get-product-form', 'get-photo-form',
                            'get-document-form', 'get-employee-form', 'update', 'copy', 'edit', 'quick-update',
                            'get-user-representatives', 'get-all-products-summary', 'get-custom-data-summary',
                            'get-custom-data-numeration', 'get-color-and-shape'],
                        'allow' => true,
                        'roles' => [Utility::ROLE_CLIENT],
                    ],
                    [
                        'actions' => ['delete', 'get-product-form', 'get-costs-form'],
                        'allow' => true,
                        'roles' => [Utility::ROLE_CLIENT],
                    ],
                    [
                        'actions' => ['summary'],
                        'allow' => true,
                        'roles' => [Utility::ROLE_CLIENT],
                        'verbs' => ['post'],
                    ],
                    [
                        'actions' => ['find'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex() {
        return $this->redirect(['order/list']);
    }

    public function actionList() {
        $request = Yii::$app->request;
        $ordersListForm = new OrdersListForm();
        $ordersListForm->load($request->get());

        $activeOrdersQuery = OrderQuery::getOrdersQuery($ordersListForm->toArray() + ['isVisibleForClient' => 1]);
        $pages = new Pagination([
            'totalCount' => $activeOrdersQuery->count(),
            'page' => $ordersListForm->page,
            'defaultPageSize' => \Yii::$app->params['defaultPageSize'],
        ]);
        $orders = $activeOrdersQuery->limit($pages->defaultPageSize)->offset($pages->page * $pages->defaultPageSize)->all();

        $ordersListData = [
            'orders' => $orders,
            'pages' => $pages,
            'ordersListForm' => $ordersListForm,
        ];

        if($request->isAjax) {
            echo json_encode([
                'view' => $this->renderAjax('inc/_orders', $ordersListData),
                'url' => Url::current([], true),
            ]);
        } else {
            $ordersListData['ordersStatusesTranslations'] = OrderStatusTranslation::find()->forLanguage(\Yii::$app->language)->visibleForClient(1)->all();
            return $this->render('list', $ordersListData);
        }
    }

    public function actionDetails($id) {
        $data = OrderQuery::getDetails($id);
        if(empty($data) ||
                !empty($data['isDeleted']) ||
                (!(Yii::$app->user->can(Utility::ROLE_CLIENT) &&
                (UserQuery::isClientOrderCreator($id, Yii::$app->user->id) ||
                UserQuery::isOrderRepresentant($id, Yii::$app->user->id))) &&
                (!UserQuery::isSalesmanAssignedToCompanyByOrderId(Yii::$app->user->id, $id) &&
                !Yii::$app->user->can(Utility::ROLE_MAIN_SALESMAN) &&
                !UserQuery::isSalesmanAssignedToOrder(Yii::$app->user->id, $id)))
        ) {
            throw new \yii\web\NotFoundHttpException(Yii::t('web', 'Element does not exist or you do not have permission.'));
        }

        $reservedProducts = WarehouseProductQuery::getReservedProductsByOrderId($id)->all();

        $contactPeople = OrderUserRepresentativeQuery::getUserRepresentativesByOrderId($id);
        $orderTypes = OrderTypeSetQuery::getOrderTypesByOrderId($id);
        $entries = OrderHistoryQuery::getOrderEntries($id);
        $salesmen = UserOrderSalesmanQuery::getSalesmenByOrderId($id);
        $attachments = OrderQuery::getAttachments($id);
        $products = OrderQuery::getOrderProducts($id, ['withArtificial' => true]);
        if(Yii::$app->params['isAttachmentForProductVisible']) {
            foreach($products as &$oneProduct) {
                $oneProduct['attachments'] = OrderQuery::getOrderProductAttachments($oneProduct['id']);
            }
        }
        $suborders = OrderQuery::getChildrenOrders($id);

        $costSum = 0;
        if(!empty($products)) {
            foreach($products as $product) {
                if(!empty($product['price'])) {
                    $costSum += $product['count'] * ($product['price'] * $product['conversionValue']);
                }
            }
        }

        $photos = [];
        $photosRaw = OrderQuery::getPhotos($id);
        if(!empty($photosRaw)) {
            $photos = array_map(function($row) {
                return [
                    'url' => $row['urlPhoto'],
                    'src' => $row['urlThumbnail'],
                    'options' => [
                        'title' => $row['description'],
                    ],
                ];
            }, $photosRaw);
        }

        $summary;
        $vats;
        OrderModel::calculateSummary($products, $summary, $vats);
        $data['visibleStatusButton'] = false;

        if(!empty($data['statusId'])) {
            $statusSuccessorId = ArrayHelper::map(OrderStatusTransition::find()->where(['order_status_predecessor_id' => $data['statusId']])->all(), 'order_status_successor_id', 'order_status_successor_id');
            $statusId = OrderStatus::find()->where(['IN', 'id', $statusSuccessorId])->andWhere(['is_visible_for_client' => 1])->one();

            $data['visibleStatusButton'] = isset($statusId) && !empty($statusId) ? true : false;
        }

        if(!empty($data['customData'])) {
            $data['customDataSummary'] = OrderTableForm::calculateTotalPriceStatic(Json::decode($data['customData']));
        }

        if(Yii::$app->params['isProductAttributesVisible'] && !empty($products)) {
            foreach($products as &$product) {
                $attributes = OrderOfferedProductAttributeQuery::getProductAttributes($product['id'], false, true);
                $product['attributes'] = null;

                if(!empty($attributes)) {
                    $attrs = [];
                    foreach($attributes as $attribute) {
                        $attrs[] = $attribute['name'] . (intval($attribute['value']) > 1 ? ': ' . $attribute['value'] : '');
                    }

                    $product['attributes'] = implode(', ', $attrs);
                }
            }
        }

        $orderStatus = Order::findOne($id)->orderHistoryLast->orderStatus->symbol;
        $isInProgress = $orderStatus == Utility::ORDER_STATUS_IN_PROGRESS;
        
        return $this->render('details', [
            'data' => $data,
            'contactPeople' => $contactPeople,
            'orderTypes' => $orderTypes,
            'entries' => $entries,
            'salesmen' => $salesmen,

public_html/customer/controllers/StorageController.php
<?php

namespace customer\controllers;


class StorageController extends \frontend\controllers\StorageController {

}

public_html/customer/views/order/create.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;
use common\helpers\StringHelper;
use common\helpers\Utility;

$this->registerJsFile('@web/js/pages/toggle-attributes.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/forms.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/order-form.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/pages/ral-colour-picker.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);

if(Yii::$app->params['isVisualisationVisible']) {
    $this->registerJsFile('@web/js/pages/order-visualisation.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
}

$this->title = StringHelper::translateOrderToOffer('web', 'Create order') . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => StringHelper::translateOrderToOffer('main', 'Orders'), 'url' => Url::to(['order/index'])];
$this->params['breadcrumbs'][] = ['label' => StringHelper::translateOrderToOffer('main', 'List of orders'), 'url' => Url::to(['order/list'])];
$this->params['breadcrumbs'][] = StringHelper::translateOrderToOffer('web', 'Create order');
?>

<div class="order-form">
	<h2 class="page-title"><?= StringHelper::translateOrderToOffer('web', 'Create order') ?></h2>
    
    <?php 
        $form = ActiveForm::begin([
            'id' => 'order-create-form',
            'action' => ['order/summary'],
            'enableAjaxValidation' => true,
            'enableClientValidation' => false,
            'options' => [
                'class' => 'form',
            ]
        ]);

        echo $form->errorSummary($invalidForms);
    ?>

    <?= Yii::$app->controller->renderPartial('inc/_basic_data', [
	    	'entities' => $entities,
	        'orderCreateForm' => $orderCreateForm, 
	        'form' => $form,
    ]) ?>
    <div class="col-xs-12" id="products">
    	<div class="row">
        <?= Yii::$app->controller->renderPartial('inc/_products', [
                'orderProductsForms' => $orderProductsForms, 
                'currencies' => $currencies,
                'constructions' => $constructions,
                'shapes' => $shapes,
                'muntins' => $muntins,
                'form' => $form,
                'orderProductsVats' => $orderProductsVats,                
                'orderProductsSummary' => $orderProductsSummary,
                'plnCurrency' =>  $plnCurrency,
                'displayFirstAttributes' => $displayFirstAttributes,
                'productAttributeForms' => !empty($productAttributeForms) ? $productAttributeForms : [],
        ]); ?>
        </div>
    </div>
    <div id="costs" class="col-xs-12">
    	<div class="row">
        <?= Yii::$app->controller->renderPartial('inc/_costs', [
                'orderCostsForms' => $orderCostsForms,
                'currencies' => $currencies,
                'constructions' => $constructions,
		        'shapes' => $shapes,
		        'muntins' => $muntins,
                'form' => $form,
                'orderCostsVats' => $orderCostsVats,
                'orderCostsSummary' =>$orderCostsSummary,
                'plnCurrency' =>  $plnCurrency,
                'displayFirstAttributes' => $displayFirstAttributes,
                'productAttributeForms' => !empty($artificialProductAttributeForms) ? $artificialProductAttributeForms : [],
        ]); ?>
        </div>
    </div>
    <div id="product-summary" class="col-xs-12">
    	<div class="row">
    		<?= Yii::$app->controller->renderPartial('inc/_productSummary', ['summary' => $summary, 'plnCurrency' => $plnCurrency]) ?>
    	</div>
    </div>
    
    <?= Yii::$app->controller->renderPartial('inc/_files', [
            'orderCreateForm' => $orderCreateForm,
            'photosForms' => $photosForms,
            'documentsForms' => $documentsForms,
            'form' => $form,
        ]);
    ?>
    <?php if(Yii::$app->params['isOrderRemarksVisible']) { ?>
        <div class="col-xs-12">
            <div class="row">
                <div class="col-sm-6">
                    <?= $form->field($orderCreateForm, 'descriptionCont')->textarea(['placeholder' => $orderCreateForm->getAttributeLabel('descriptionCont'), 'maxLength' => true]) ?>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="col-sm-12">
        <?= Html::a(Yii::t('web', 'Cancel'), Url::to(['order/list']), ['class' => 'btn btn-default']) ?>
        <input type="hidden" name="save" value="0"/>
        <input type="hidden" name="OrderCreateForm[orderId]" value=""/>
        <button  type="button" class="btn btn-primary pull-right" id="add-order"><?= Yii::t('web', 'Next') ?></button>
        <div class="save-order-div">
            <div id="info">
                .....
            </div>
            <button class="btn btn-primary pull-right" id="save-order" style="display: <?php echo Yii::$app->params['isOrderQuickSaveVisible'] ? 'block' : 'none' ?>">
                <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
            </button>
        </div>
    </div>

    <?php ActiveForm::end() ?>
</div>

<?php $this->registerJs('
    (function() {
        var dynamicForm = new DynamicForm("order-create-form");
        dynamicForm.activateRemoveButtons();
        dynamicForm.activateAddItemButtons();

        OrderForm.activateEmployeesChooser($("#employee-select"), $("#selected-employees"));
        OrderForm.save("order-create-form", "OrderCreateForm[orderId]", "<div class=\"alert alert-success\" role=\"alert\">'.Yii::t('web', 'Success save').'</div>", "<div class=\"alert alert-danger\" role=\"alert\">'.Yii::t('web', 'Error').'</div>");
        dynamicForm.activatePhotoUpload();
        dynamicForm.activateDocumentUpload();
        dynamicForm.activateProductFileUpload();
        OrderForm.initRecalculate("OrderProductForm", "'. Url::to(['order/get-products-form']).'", "order-create-form", "products", "ProductAttributeForm");
        OrderForm.initRecalculate("OrderCostForm", "'.Url::to(['order/get-costs-form']).'", "order-create-form", "costs", "ArtificialProductAttributeForm");
		OrderForm.initRecalculateSummary("'.Url::to(['order/get-all-products-summary']).'", "product-summary");
		OrderForm.initRecalculateCustomData("'.Url::to(['order/get-custom-data-summary']).'", "'.Url::to(['order/get-custom-data-numeration']).'", "custom-tables");
        toggleAttributes();
        handleColourPicker("' . Url::to(['colour/get-modal-content']) . '");
    })();
    ', View::POS_READY);
    
    $this->registerJs('
    	$("#ordercreateform-clientid").trigger("select2:select");
    ', View::POS_END);
    $this->registerJs('        
    	$("#ordercreateform-clientid").trigger("select2:select");     
    ', View::POS_END);

    if(Yii::$app->params['isOrderProductDimensionsVisible']) {
        $this->registerJs('     
        $(document).ready(function() {
            localStorage.removeItem("lastId");
                
            $(document).on("keydown", function (e) {
                if (e.which == 9) {
                    e.preventDefault();
                    if($("#" + e.target.id).hasClass("tab-me")) {
                
                        var $others = $("#" + e.target.id).parents().addBack().nextAll().find("*").addBack().filter(".tab-me");
                
                        if($others.length == 0) {
                            $others = $(document).find(".tab-me");
                        }
                
                        $others.first().focus();
                        localStorage.setItem("lastId", $others.first().attr("id"));
                    }
                }
            });
        });
                
        ', View::POS_END);
    }
?>
<?php
$this->registerJsFile(
    '@web/js/maskInput/jquery.mask.min.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>

<?php
if(Yii::$app->params['isVisualisationVisible']) {
    $shapes = implode('-', Utility::getShapes());
    $this->registerJs('init("' . Url::to(['order/get-color-and-shape']) . '", "' . $shapes . '", "'.Url::to(['storage/index']).'");', View::POS_END);
}
?>

public_html/customer/views/order/update.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;
use common\helpers\StringHelper;
use common\helpers\Utility;

$this->registerJsFile('@web/js/forms.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/order-form.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/pages/toggle-attributes.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/pages/ral-colour-picker.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);

if(Yii::$app->params['isVisualisationVisible']) {
    $this->registerJsFile('@web/js/pages/order-visualisation.js?' . uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
}

$this->title = Yii::t('web', 'Update status') . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => StringHelper::translateOrderToOffer('main', 'Orders'), 'url' => Url::to(['order/index'])];
$this->params['breadcrumbs'][] = ['label' => StringHelper::translateOrderToOffer('main', 'List of orders'), 'url' => Url::to(['order/list'])];
$this->params['breadcrumbs'][] = ['label' => StringHelper::translateOrderToOffer('web', 'Order details'), 'url' => Url::to(['order/details', 'id' => $id])];
$this->params['breadcrumbs'][] = StringHelper::translateOrderToOffer('web', 'Update order');
?>

<div class="order-form" id="order-update">
    <h2 class="page-title"><?= StringHelper::translateOrderToOffer('web', 'Update order') ?></h2>

    <?php
    $form = ActiveForm::begin([
                'id' => 'order-update-form',
                'enableAjaxValidation' => true,
                'enableClientValidation' => false,
                'options' => [
                    'class' => 'form',
                ]
    ]);

    echo $form->errorSummary($invalidForms);
    echo $form->field($orderCreateForm, 'orderId')->hiddenInput()->label(false);
    ?>

    <h3><?= Yii::t('web', 'Products') ?></h3>
    <div id="products">
        <?php
        echo Yii::$app->controller->renderPartial('inc/_products', [
            'orderProductsForms' => $orderProductsForms,
            'currencies' => $currencies,
            'form' => $form,
            'constructions' => $constructions,
            'shapes' => $shapes,
            'muntins' => $muntins,
            'orderProductsVats' => $orderProductsVats,
            'orderProductsSummary' => $orderProductsSummary,
            'plnCurrency' => $plnCurrency,
            'displayFirstAttributes' => $displayFirstAttributes,
            'productAttributeForms' => !empty($productAttributeForms) ? $productAttributeForms : [],
        ]);
        ?>
    </div>
    <div id="costs">
        <?=
        Yii::$app->controller->renderPartial('inc/_costs', [
            'displayFirstAttributes' => $displayFirstAttributes,
            'orderCostsForms' => $orderCostsForms,
            'currencies' => $currencies,
            'form' => $form,
            'orderCostsVats' => $orderCostsVats,
            'orderCostsSummary' => $orderCostsSummary,
            'plnCurrency' => $plnCurrency,
            'constructions' => $constructions,
            'shapes' => $shapes,
            'muntins' => $muntins,
            'productAttributeForms' => !empty($artificialProductAttributeForms) ? $artificialProductAttributeForms : [],
        ])
        ?>
    </div>

    <div id="product-summary">
        <?= Yii::$app->controller->renderPartial('inc/_productSummary', ['summary' => $summary, 'plnCurrency' => $plnCurrency]) ?>
    </div>

    <?= Yii::$app->controller->renderPartial('inc/_status', ['orderHistoryForm' => $orderHistoryForm, 'orderStatuses' => $orderStatuses, 'form' => $form]) ?>

    <?= $form->field($orderCreateForm, 'isInvoiced')->checkbox() ?>

    <?=
    Yii::$app->controller->renderPartial('inc/_files', [
        'rderCreateForm' => $orderCreateForm,
        'photosForms' => $photosForms,
        'documentsForms' => $documentsForms,
        'readOnlyPhotosForms' => $oldPhotosForms,
        'readOnlyDocumentsForms' => $oldDocumentsForms,
        'form' => $form,
    ]);
    ?>

    <div class="col-sm-12">
        <?= Html::a(Yii::t('web', 'Cancel'), Url::to(['order/details', 'id' => $id]), ['class' => 'btn btn-default']) ?>
        <input type="hidden" name="save" value="0"/>
        <input type="hidden" name="OrderHistoryForm[orderHistoryId]" value=""/>
        <button type="button" class="btn btn-primary pull-right" id="update-order"><?= Yii::t('main', 'Save') ?></button>
        <div class="save-order-div">
            <div id="info">
                .....
            </div>
            <button class="btn btn-primary pull-right" id="save-order" style="display: <?php echo Yii::$app->params['isOrderQuickSaveVisible'] ? 'block' : 'none' ?>">
                <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
            </button>
        </div>
    </div>

    <?php ActiveForm::end() ?>
</div>

<?php $this->registerJs('
    (function() {
        var dynamicForm = new DynamicForm("order-update-form");
        dynamicForm.activateRemoveButtons();
        dynamicForm.activateAddItemButtons();

        OrderForm.activateEmployeesChooser($("#employee-select"), $("#selected-employees"));

        dynamicForm.activatePhotoUpload();
        dynamicForm.activateDocumentUpload();
        dynamicForm.activateProductFileUpload();
		OrderForm.save("order-update-form", "OrderHistoryForm[orderHistoryId]", "<div class=\"alert alert-success\" role=\"alert\">' . Yii::t('web', 'Success save') . '</div>", "<div class=\"alert alert-danger\" role=\"alert\">' . Yii::t('web', 'Error') . '</div>");
        OrderForm.initRecalculate("OrderProductForm", "' . Url::to(['order/get-products-form']) . '", "order-update-form", "products", "ProductAttributeForm");
        OrderForm.initRecalculate("OrderCostForm", "' . Url::to(['order/get-costs-form']) . '", "order-update-form", "costs", "ArtificialProductAttributeForm");
		OrderForm.initRecalculateSummary("' . Url::to(['order/get-all-products-summary']) . '", "product-summary");
		OrderForm.initRecalculateCustomData("' . Url::to(['order/get-custom-data-summary']) . '", "' . Url::to(['order/get-custom-data-numeration']) . '", "custom-tables");
        toggleAttributes();
        handleColourPicker("' . Url::to(['colour/get-modal-content']) . '");
    })();
    ', View::POS_READY);
?>

<?php
$this->registerJsFile(
        '@web/js/maskInput/jquery.mask.min.js', ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>

<?php
if(Yii::$app->params['isVisualisationVisible']) {
    $shapes = implode('-', Utility::getShapes());
        $this->registerJs('init("' . Url::to(['order/get-color-and-shape']) . '", "' . $shapes . '", "'.Url::to(['storage/index']).'");', View::POS_END);
}
?>