public_html/frontend/models/TaskForm.php
<?php

namespace frontend\models;

use Yii;
use yii\base\Model;
use common\models\ar\Task;
use frontend\helpers\AdditionalFieldHelper;
use common\models\ar\TaskData;
use common\models\aq\TaskPriorityQuery;
use common\models\aq\TaskTypeReferenceQuery;
use frontend\helpers\UserHelper;
use common\models\aq\TaskQuery;
use common\models\aq\TaskTypeQuery;
use common\models\ar\TaskTypeReference;
use common\alerts\TaskDeadlineAlertHandler;
use common\models\ar\Product;

class TaskForm extends Model {

	const SCENARIO_ADD = 'add';
	const SCENARIO_EDIT = 'edit';

    public $id;
    public $title;
    public $priorityValue;
    public $message;
    public $dateReminder;
    public $dateDeadline;
    public $userNotifiedId;
    public $taskTypeId;
    public $fields = [];
    
    public $userNotifiedData = [];
    public $fieldsData = [];

	public function __construct($task = null, $config = []) {
		if(!empty($task)) {
			$this->loadData($task);
		}

		parent::__construct($config);
	}

	public function scenarios() {
		$scenarios = parent::scenarios();
		$scenarios[self::SCENARIO_ADD] = ['title', 'priorityValue', 'message', 'dateReminder', 'dateDeadline', 'userNotifiedId', 'taskTypeId', 'fields'];
		$scenarios[self::SCENARIO_EDIT] = ['id', 'title', 'priorityValue', 'message', 'dateReminder', 'dateDeadline', 'userNotifiedId', 'taskTypeId', 'fields'];
		return $scenarios;
	}

	public function rules() {
		return [
				[['title', 'priorityValue', 'message', 'taskTypeId'], 'required'],
				[['title'], 'string', 'max' => 128],
				[['message'], 'string', 'max' => 2048],
				[['priorityValue', 'userNotifiedId', 'taskTypeId'], 'integer'],
				[['dateReminder', 'dateDeadline'], 'safe'],
				[['fields'], 'each', 'rule' => ['integer']],
				[['fields'], 'each', 'rule' => ['default', 'value' => null]],
				['fields', 'validateAdditionalField'],
				[['dateReminder', 'dateDeadline', 'userNotifiedIds'], 'default', 'value' => null],
		];
	}

	public function validateAdditionalField($attribute, $params) {
		$errors = AdditionalFieldHelper::validateAdditionalFields($this->fields, TaskTypeReferenceQuery::getAdditionalFieldsByTaskTypeId($this->taskTypeId));
		if(!empty($errors)) {
			foreach($errors as $error) {
				$this->addError('fields['.$error['id'].']', $error['message']);
			}
		}
	}

    public function attributeLabels() {
        return [
	            'title' => Yii::t('main', 'Title'),
        		'priorityValue' => Yii::t('main', 'Priority'),
        		'message' => Yii::t('main', 'Detailed task description'),
        		'dateDeadline' => Yii::t('main', 'Deadline date'),
        		'dateReminder' => Yii::t('main', 'Reminder date'),
        		'userNotifiedId' => Yii::t('main', 'Employee receiving task'),
        		'taskTypeId' => Yii::t('main', 'Task type'),
        ];
    }

	public function saveData() {
		$task = null;
		if(!empty($this->id)) {
			$task = Task::findOne($this->id);
		}

		if(empty($task)) {
			$task = new Task();
		}
		
		$transaction = Yii::$app->db->beginTransaction();
		try {
			$isDateChanged = $this->isEditScenarioSet() && 
					((new \DateTime($task->date_reminder))->format('Y-m-d') != $this->dateReminder
					|| (new \DateTime($task->date_deadline))->format('Y-m-d') != $this->dateDeadline);
			
			$priorities = TaskPriorityQuery::getAllOrdered();
			$task->task_priority_id = $priorities[$this->priorityValue - 1]->id;

			$task->task_type_id = $this->taskTypeId;
			$task->user_id = Yii::$app->user->id;
			$task->title = $this->title;
			$task->message = $this->message;
			$task->user_notified_id = $this->userNotifiedId;
			$task->date_reminder = $this->dateReminder;
			$task->date_deadline = $this->dateDeadline;
			$task->is_active = 1;

			if(!$task->save()) {
				Yii::error(print_r($task->getErrors(), true));
				throw new \Exception('Error during saving the task.');
			}
			
			if(!empty($task->taskDatas)) {
				TaskData::deleteAll(['task_id' => $task->id]);
			}

			if(!empty($this->fields)) {
				foreach($this->fields as $k => $v) {
					if(!empty($v) && TaskTypeReference::findOne($k)->task_type_id == $this->taskTypeId) {
						$data = new TaskData();
						$data->task_id = $task->id;
						$data->task_type_reference_id = $k;
						$data->referenced_object_id = $v;
						if(!$data->save()) {
							Yii::error(print_r($data->getErrors(), true));
							throw new \Exception('Error during saving the field.');
						}
					}
				}
			}
			
			if($isDateChanged) {
				TaskDeadlineAlertHandler::check([
						'taskId' => $task->id,
						'forceIfIncomplete' => true,
				]);
			}

			$transaction->commit();
		}
		catch(\Exception $e) {
			$transaction->rollBack();
			Yii::error($e->getMessage());
			Yii::error($e->getTraceAsString());
			throw new \Exception('Could not save task data');
		}
	}

    public function loadData($task) {
    	$this->id = $task->id;
    	$this->title = $task->title;
    	$this->priorityValue = $task->task_priority_id;
    	$this->message = $task->message;
    	if(!empty($task->date_reminder)) {
    		$this->dateReminder = (new \DateTime($task->date_reminder))->format('Y-m-d');
    	}
    	if(!empty($task->date_deadline)) {
    		$this->dateDeadline = (new \DateTime($task->date_deadline))->format('Y-m-d');
    	}
    	$this->userNotifiedId = $task->user_notified_id;
    	$this->taskTypeId = $task->task_type_id;
    	
    	if(!empty($task->userNotified)) {
    		$this->userNotifiedData = [$task->user_notified_id => UserHelper::getPrettyUserName($task->userNotified->email, 
    				$task->userNotified->first_name, $task->userNotified->last_name)];
    	}
    	
    	$additionalFields = TaskTypeReferenceQuery::getAdditionalFieldsByTaskTypeIds(
    			array_column(TaskTypeQuery::getAllTypes(), 'id'));
    	foreach($additionalFields as $af) {
    		$this->fields[$af['id']] = null;
    	}
    	
    	$references = TaskQuery::getTaskReferences($task->id);
    	if(!empty($references)) {
    		foreach($references as $ref) {
    			$name = $ref['name'];
    			if($ref['table'] == 'product') {
    				$name = Product::findOne($ref['id'])->getTranslation()->name;
    			}
    			
    			$this->fields[$ref['referenceId']] = $ref['id'];
    			$this->fieldsData[$ref['referenceId']] = ['id' => $ref['id'], 'name' => $name];
    		}
    	}
    }

    public function setAddScenario() {
    	$this->setScenario(self::SCENARIO_ADD);
    }

    public function setEditScenario() {
    	$this->setScenario(self::SCENARIO_EDIT);
    }

    public function isEditScenarioSet() {
    	return $this->getScenario() == self::SCENARIO_EDIT;
    }

    public function setAdditionalFields($additionalFields, $initialValues = []) {
    	foreach($additionalFields as $field) {
    		$this->fields[$field['id']] = isset($initialValues[$field['id']]) ? $initialValues[$field['id']]['id'] : null;
    	}
    }
}

public_html/frontend/controllers/TaskController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\components\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use common\helpers\Utility;
use common\models\aq\TaskPriorityQuery;
use frontend\models\TaskForm;
use common\models\aq\TaskTypeQuery;
use common\models\aq\TaskTypeReferenceQuery;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii\widgets\ActiveForm;
use common\models\aq\TaskQuery;
use frontend\models\TaskListForm;
use yii\data\Pagination;
use yii\helpers\Url;
use common\models\ar\Task;
use yii\db\Expression;
use frontend\helpers\UserHelper;
use common\alerts\TaskDeadlineAlertHandler;
use common\models\ar\TaskHistory;
use common\models\ar\TaskDataHistory;
use common\models\ar\TaskData;
use common\models\ar\AlertHistory;
use common\models\ar\Alert;
use common\models\ar\User;
use common\models\ar\Product;
use common\models\ar\TaskType;
use frontend\logic\TaskLogic;
use common\models\ar\Order;

class TaskController extends Controller {

	public function behaviors() {
		$allActions = ['create', 'short-list', 'get-details', 'complete', 'delete', 'edit'];

		return [
				'access' => [
						'class' => AccessControl::className(),
						'only' => $allActions,
						'rules' => [
								[
										'actions' => $allActions,
										'allow' => true,
										'roles' => [Utility::ROLE_SALESMAN, Utility::ROLE_STOREKEEPER],
								],
						],
				],
				'verbs' => [
						'class' => VerbFilter::className(),
						'actions' => [
								'complete' => ['post'],
								'delete' => ['post'],
						],
				],
		];
	}

	public function actionShortList() {
		$request = Yii::$app->request;
        $listForm = new TaskListForm();
        $listForm->load($request->get());

        $itemsQuery = TaskQuery::getActiveTasksQuery(Yii::$app->user->id, $listForm->toArray());
        $pages = new Pagination([
        		'totalCount' => $itemsQuery->count(),
        		'page' => $listForm->page,
        		'defaultPageSize' => 10,
        ]);
        $items = $itemsQuery->limit(10)->offset(0)->all();

        $taskLogic = new TaskLogic();
        $items = $taskLogic->processTasks($items);
        
        $listData = [
        		'items' => $items,
        		'pages' => $pages,
        		'listForm' => $listForm,
        ];

        if($request->isAjax && !Yii::$app->request->get('dashboard')) {
        	return json_encode([
        			'view' => $this->renderAjax('_tasks', $listData),
        			'url' => Url::current([], true),
        	]);
        }
		$listData['taskTypes'] = ArrayHelper::map(TaskTypeQuery::getAllTypes(), 'id', 'name');
		$listData['taskTypes'] = [ 0 => Yii::t('web', 'All')] + $listData['taskTypes'];
		if(Yii::$app->request->get('dashboard')) {
			return $this->renderAjax('shortList', $listData);
		}
        else {
        	return $this->render('shortList', $listData);
        }
	}

	public function actionCreate($taskTypeId = null, $userNotifiedId = null, $productId = null, $orderId = null) {
		$model = new TaskForm();
		$model->setAddScenario();

		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
		
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			try {
				$model->saveData();
				
				Yii::$app->getSession()->setFlash('success', Yii::t('web', 'Task has been added successfully.'));
				
				$taskType = TaskType::findOne($model->taskTypeId);
				if($taskType->symbol == Utility::TASK_TYPE_ASSOCIATED_WITH_ORDER && !empty($model->fields) && !empty(yii::$app->request->get('orderId'))) {
					return $this->redirect(['order/details', 'id' => $model->fields[2]]);
				}
				
				return $this->redirect(['dashboard/index']);
			}
			catch(\Exception $e) {
				Yii::$app->getSession()->setFlash('error', Yii::t('web', 'Task data cannot be saved. Check provided values.'));
				Yii::error($e->getMessage());
				Yii::error($e->getTraceAsString());
			}
		}
		
		if(!empty($taskTypeId)) {
			$model->taskTypeId = $taskTypeId;
			
			$taskType = TaskType::findOne($taskTypeId);
			if($taskType->symbol == Utility::TASK_TYPE_ORDER_PRODUCT) {
				$model->title = Yii::t('web', 'Product to order');
				$model->message = Yii::t('web', 'Please order the product given below.');
			}
		}
		
		$userNotifiedData = null;
		if(!empty($userNotifiedId)) {
			$model->userNotifiedId = $userNotifiedId;
			$user = User::findOne($userNotifiedId);
			$userNotifiedData = [$userNotifiedId => UserHelper::getPrettyUserName($user->email, $user->first_name, $user->last_name)];
		}

		$taskTypes = TaskTypeQuery::getAllTypes();
		$fieldArrays = $this->getAdditionalFields($model, $taskTypes, true, $productId, $orderId, $taskTypeId);
		
		return $this->render('form', [
				'model' => $model,
				'priorityData' => $this->getPriorityData(),
				'taskTypes' => $taskTypes,
				'fields' => $fieldArrays['fields'],
				'userNotifiedData' => $userNotifiedData,
				'fieldsInitialValues' => $fieldArrays['initials'],
		]);
	}
	
	public function actionEdit($id) {
		$task = Task::findOne($id);
		$userId = Yii::$app->user->id;
		if(empty($task) || !empty($task->is_complete) ||  (!empty($task->userNotified) && $task->user_notified_id != $userId) || 
				(empty($task->userNotified) && $task->user_id != $userId)) {
			throw new \yii\web\NotFoundHttpException(Yii::t('web', 'Element does not exist or you do not have permission.'));
		}
		
		$model = new TaskForm($task);
		$model->setEditScenario();
	
		if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
			Yii::$app->response->format = Response::FORMAT_JSON;
			return ActiveForm::validate($model);
		}
	
		if($model->load(Yii::$app->request->post()) && $model->validate()) {
			try {
				$model->saveData();
				Yii::$app->getSession()->setFlash('success', Yii::t('web', 'Task has been updated successfully.'));
	
				return $this->redirect(['dashboard/index']);
			}
			catch(\Exception $e) {
				Yii::$app->getSession()->setFlash('error', Yii::t('web', 'Task data cannot be saved. Check provided values.'));
				Yii::error($e->getMessage());
				Yii::error($e->getTraceAsString());
			}
		}
		
		$taskTypes = TaskTypeQuery::getAllTypes();
		$fieldArrays = $this->getAdditionalFields($model, $taskTypes, false);
		
		return $this->render('form', [
				'model' => $model,
				'priorityData' => $this->getPriorityData(),
				'taskTypes' => $taskTypes,
				'fields' => $fieldArrays['fields'],
				'userNotifiedData' => $model->userNotifiedData,
				'fieldsInitialValues' => $model->fieldsData,
		]);
	}
	
	private function getAdditionalFields($model, $taskTypes, $saveFields = true, $productId = null, $orderId = null, $taskTypeId = null) {
		$fields = TaskTypeReferenceQuery::getAdditionalFieldsByTaskTypeIds(ArrayHelper::getColumn($taskTypes, 'id'));
		$fieldsInitialValues = [];
		
		if(!empty($fields)) {
			if((!empty($productId) || !empty($orderId)) && !empty($taskTypeId)) {
				foreach($fields as $field) {
					if($field['taskTypeId'] == $taskTypeId) {
						if($field['nameTable'] == 'product') {
							$product = Product::findOne($productId);
							$productTranslation = $product->getTranslation();
							if(!empty($productTranslation)) {
								$productName = $productTranslation->name;
							}
							else {
								$productName = $product->symbol;
							}
			
							$fieldsInitialValues[$field['id']] = ['id' => $productId, 'name' => $productName];
							break;
						}
						elseif($field['nameTable'] == 'order') {
							$order = Order::findOne($orderId);
							$fieldsInitialValues[$field['id']] = ['id' => $orderId, 'name' => $order->title];
							break;
						}
					}
				}
			}
				
			if($saveFields) {
				$model->setAdditionalFields($fields, $fieldsInitialValues);
			}
		}
		
		return [ 'fields' => $fields, 'initials' => $fieldsInitialValues ];
	}

	public function actionGetDetails($id) {
		if(!Yii::$app->request->isAjax) {
			return '';
		}

		$taskId = Yii::$app->request->get('id');
		$data = TaskQuery::getDetails($taskId);
		if(empty($data)) {
			return Yii::t('web', 'No detailed data about task.');
		}
		
		return $this->renderAjax('inc/details', [
				'data' => $data,
		]);
	}

	public function actionComplete() {
		$id = Yii::$app->request->post('id');

		try {
			if(!TaskQuery::isTaskVisibleByUserId($id, Yii::$app->user->id)) {
				throw new Exception('Task '.$id.' is unavailable for user '.Yii::$app->user->id.' to complete.');
			}

			$task = Task::findOne($id);
			$task->date_completion = new Expression('NOW()');
			$task->user_completing_id = Yii::$app->user->id;
			$task->is_complete = 1;
			$task->save();
			
			TaskDeadlineAlertHandler::check(['taskId' => $task->id]);
			
			if(strpos(Yii::$app->request->getReferrer(), 'order/details') !== false) {
	        	return $this->redirect(Yii::$app->request->getReferrer());
	        }
		}
		catch(\Exception $e) {
			Yii::error(print_r($e->getMessage(), true));
			Yii::$app->getSession()->setFlash('error', Yii::t('web', 'There is no task with such identifier.'));
		}
	}

	public function actionDelete() {
		$id = Yii::$app->request->post('id');

		$transaction = Yii::$app->db->beginTransaction();
		try {
			if(!TaskQuery::isTaskVisibleByUserId($id, Yii::$app->user->id)) {
				throw new \Exception('Task '.$id.' is unavailable for user '.Yii::$app->user->id.' to delete.');
			}

			$task = Task::findOne($id);
			
			$taskHistory = new TaskHistory();
			$taskHistory->task_type_id = $task->task_type_id;
			$taskHistory->task_priority_id = $task->task_priority_id;
			$taskHistory->user_id = $task->user_id;
			$taskHistory->title = $task->title;
			$taskHistory->message = $task->message;

public_html/frontend/views/task/_tasks.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\web\View;
use yii\helpers\Url;
use common\helpers\StringHelper;
?>

<?php
if (empty($items)) { ?>
	<label><?= Yii::t('web', 'No search results');?></label>
	<br><br>
<?php }
else { ?>
	<div class="table-responsive">
	    <table class="table">
	        <tbody>
	            <?php foreach($items as $item): ?>
	                <tr data-id="<?= $item['id'] ?>">
	                	<td data-id="<?= $item['id'] ?>" class="<?= !empty($item['isComplete']) ? 'strikeout' : '' ?> <?= $item['isWarning'] ? 'warned' : '' ?>">
	                		<span class="checkbox-completion-column">
	                			<?= Html::checkbox('checkbox-complete-'.$item['id'], !empty($item['isComplete']), [
	                					'class' => 'checkbox-completion',
	                					'data-id' => $item['id'],
	                					'disabled' => !empty($item['isComplete']),
	                			]); ?>
	                		</span>
	                    	<span class="task-title not-extended"><?= Html::encode($item['title']) ?></span>
	                    	<div class="task-details" style="display: none"></div>
	                    	<?php if(!empty($item['dateDeadline'])) { ?>
	                    		<span class="task-date pull-right"><?= StringHelper::getFormattedDateFromDate(Html::encode($item['dateDeadline']), false) ?></span>
	                    	<?php } ?>
	                    </td>
	                    <td>
	                    	<?= Html::a('<span class="base-icon alert-icon task-edit-icon task-edit"></span>', 
	                    			Url::to(['task/edit', 'id' => $item['id']]), 
	                    			['class' => 'task-edit', 'data-id' => $item['id'], 
	                    			'style' => 'display: '.(empty($item['isComplete']) ? 'inline-block' : 'none')]) ?>
	                    	<span class="base-icon alert-icon delete-icon task-deletion" data-id="<?= $item['id'] ?>"
	                    		style="display: <?= !empty($item['isComplete']) ? 'inline-block' : 'none' ?>"></span>
	                    </td>
	                </tr>
	            <?php endforeach ?>
	        </tbody>
	    </table>
	</div>
<?php }?>

<input class="dynamic-table-sort-dir" type="hidden" name="<?= Html::getInputName($listForm, 'sortDir') ?>" value="<?= $listForm->sortDir ?>" />
<input class="dynamic-table-sort-field" type="hidden" name="<?= Html::getInputName($listForm, 'sortField') ?>" value="<?= $listForm->sortField ?>" />
<input class="dynamic-table-page" type="hidden" name="<?= Html::getInputName($listForm, 'page') ?>" value="<?= $listForm->page ?>" />

public_html/frontend/views/task/shortList.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->title = Yii::t('web', 'List of tasks') . ' - ' . Yii::$app->name;

$this->registerJsFile('@web/js/dynamic-table.js?'.uniqid(), []);
$this->registerJsFile('@web/js/pages/task-short-list.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

<div id="task-short-list-wrapper">
    <div id="task-short-list-table" class="dynamic-table">
        <div class="row dynamic-table-filters">
            <div class="col-xs-3">
                    <div class="form-group">
                		<?=
                			Html::activeDropDownList($listForm, 'taskTypeId', $taskTypes, ['class' => 'dynamic-table-filter form-control']);
                		?>
                    </div>
            </div>
            <div class="col-xs-6 text-center"><p class=""><?= Yii::t('web', 'List of tasks') ?></h2></div>
            <div class="col-xs-3 text-right">
                <?= Html::a('<span class="icon-img plus-icon" aria-hidden="true"></span>', ['task/create'], ['class' => 'base-icon alert-icon add-task-icon']) ?>
            </div>
        </div>
        <div class="dynamic-table-data">
            <?= Yii::$app->controller->renderPartial('_tasks', [
	                'items' => $items,
	                'pages' => $pages,
	                'listForm' => $listForm,
            ]) ?>
        </div>
    </div>

    <?php /*$this->registerJs('
            	var table = new dynamicTable("task-short-list-table", "'.Url::to(['task/short-list']).'", 
            		{url: "'.(Yii::$app->request->get('dashboard') ? Url::to(['dashboard/index']) : null).'"});
            ', View::POS_END)*/ 
    ?>
</div>

<?php
$this->registerJs('
		var table = new dynamicTable("task-short-list-table", "'.Url::to(['task/short-list']).'", 
            		{url: "'.(Yii::$app->request->get('dashboard') ? Url::to(['dashboard/index']) : null).'"});	
		initDynamicFeatures("'.Url::to(['task/']).'", "task-short-list-table");
', View::POS_END);
?>