public_html/frontend/controllers/ProductionPathController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Url;
use frontend\components\Controller;
use frontend\logic\ProductionPathLogic;
use frontend\models\ProductionPathListForm;
use frontend\logic\ProductAttributeTypeLogic;
use common\models\ar\Language;
use common\models\ar\ProductionPath;
use common\models\ar\ProductionPathStep;
use common\models\ar\ProductionPathTranslation;
use common\models\ar\OfferedProduct;
use common\models\aq\ProductionPathQuery;
use common\models\aq\ProductionPathStepQuery;
use common\models\ar\ProductionPathStepAttribute;
use common\helpers\RandomSymbolGenerator;
use common\helpers\Utility;

class ProductionPathController extends Controller {

    public function behaviors() {
        $allActions = ['index', 'list', 'create', 'edit', 'save-step-path', 'get-production-path-steps', 'details', 'get-attributes-for-production-path-steps', 'delete'];

        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $allActions,
                'rules' => [
                    [
                        'actions' => $allActions,
                        'allow' => Yii::$app->params['isProductionVisible'],
                        'roles' => [Utility::ROLE_WORKER],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex() {
        return $this->redirect(['production-path/list']);
    }

    public function actionList() {
        $request = Yii::$app->request;
        $listForm = new ProductionPathListForm();
        $listForm->load($request->get());

        $itemsQuery = ProductionPathQuery::getProductionPathsQuery($listForm->toArray());
        $pages = new Pagination([
            'totalCount' => $itemsQuery->count(),
            'page' => $listForm->page,
            'defaultPageSize' => \Yii::$app->params['defaultPageSize'],
        ]);
        $items = $itemsQuery->limit($pages->defaultPageSize)->offset($pages->page * $pages->defaultPageSize)->all();

        $listData = [
            'items' => $items,
            'pages' => $pages,
            'listForm' => $listForm,
        ];

        if($request->isAjax) {
            echo json_encode([
                'view' => $this->renderAjax('_productionPaths', $listData),
                'url' => Url::current([], true),
            ]);
        } else {
            return $this->render('list', $listData);
        }
    }

    public function actionDetails($id) {
        $data = ProductionPathQuery::getDetails($id);

        if(empty($data)) {
            throw new \yii\web\NotFoundHttpException(Yii::t('web', 'Element does not exist or you do not have permission.'));
        }

        return $this->render('details', [
                    'data' => $data,
                    'id' => $id
        ]);
    }

    public function actionCreate() {
        return $this->render('create', [
        ]);
    }

    public function actionEdit($id) {
        return $this->render('edit', ['id' => $id]);
    }

    public function actionSaveStepPath() {
        $request = Yii::$app->request;
        $nodes = $request->post('nodes');
        $pathName = $request->post('pathName');
        $productionPathId = $request->post('productionPathId');
        $attributes = $request->post('attributes');

        $languageId = Language::find()->where(['symbol' => Yii::$app->language])->one()->id;

        $productionPathLogic = new ProductionPathLogic();
        $transaction = Yii::$app->db->beginTransaction();

        try {
            if(empty($productionPathId)) {
                $path = new ProductionPath();
                $path->symbol = RandomSymbolGenerator::generate(ProductionPath::className(), 'symbol', 32);
                $path->save();

                $pathTranslation = new ProductionPathTranslation();
                $pathTranslation->name = $pathName;
                $pathTranslation->language_id = $languageId;
                $pathTranslation->production_path_id = $path->id;
                $pathTranslation->save();
                $productionPathId = $path->id;
            } else {
                $pathTranslation = ProductionPathTranslation::findOne(['production_path_id' => $productionPathId, 'language_id' => $languageId]);
                $pathTranslation->name = $pathName;
                $pathTranslation->save();
            }


            $oldSteps = ProductionPathStep::findAll(['production_path_id' => $productionPathId]);
            foreach($oldSteps as $oldStep) {
                ProductionPathStepAttribute::deleteAll(['production_path_step_id' => $oldStep['id']]);
            }

            ProductionPathStep::deleteAll(['production_path_id' => $productionPathId]);

            $attributes = $productionPathLogic->convertAttributsToNodes($attributes);
            foreach($nodes as &$node) {
                $pathSteps = new ProductionPathStep();
                $pathSteps->production_path_id = $productionPathId;
                $pathSteps->activity_id = $node['activityId'];
                $pathSteps->is_requirement_type_or = 0;

                if(isset($attributes[$node['id']]) && !empty($attributes[$node['id']])) {
                    $pathSteps->attribute_needed_ids = isset($attributes[$node['id']]['needed']) && !empty($attributes[$node['id']]['needed']) ? $attributes[$node['id']]['needed'] : null;
                    $pathSteps->attribute_forbidden_ids = isset($attributes[$node['id']]['forbidden']) && !empty($attributes[$node['id']]['forbidden']) ? $attributes[$node['id']]['forbidden'] : null;
                }

                $pathSteps->save();

                $node['tmp_id'] = $node['id'];
                $node['id'] = $pathSteps->id;
            }

            $new_nodes = $productionPathLogic->convertNodeIdsToStepIds($nodes);

            foreach($new_nodes as $n) {
                $pathSteps = ProductionPathStep::findOne($n['id']);
                $pathSteps->step_successor_ids = empty($n['successor_ids']) ? null : $n['successor_ids'];
                $pathSteps->step_required_ids = empty($n['required_ids']) ? null : $n['required_ids'];
                $pathSteps->save();
            }

            $steps = ProductionPathStepQuery::getByProductionPathId($productionPathId);
            $sortSteps = implode(',', $productionPathLogic->sortTopologically($steps));

            $productionPath = ProductionPath::findOne($productionPathId);
            $productionPath->topological_order = $sortSteps;
            $productionPath->save();

            foreach($new_nodes as $n) {
                if(isset($attributes[$n['tmp_id']]) && !empty($attributes[$n['tmp_id']])) {
                    $unblockAttributes = isset($attributes[$n['tmp_id']]['unblock']) && !empty($attributes[$n['tmp_id']]['unblock']) ? $attributes[$n['tmp_id']]['unblock'] : '';
                    $unblockAttributes = explode(',', $unblockAttributes);
                    foreach($unblockAttributes as $unblockAttribute) {
                        $pathStepAttribute = new ProductionPathStepAttribute();
                        $pathStepAttribute->production_path_step_id = $n['id'];
                        $pathStepAttribute->product_attribute_type_id = $unblockAttribute;
                        $pathStepAttribute->save();
                    }
                }
            }

            $transaction->commit();

            Yii::$app->getSession()->setFlash('success', Yii::t('main', 'Production path has been save.'));
            return $this->redirect(['details', 'id' => $productionPathId]);
        } catch(\Exception $e) {
            $transaction->rollBack();
            Yii::error($e->getMessage());
            Yii::error($e->getTraceAsString());
            Yii::$app->getSession()->setFlash('error', Yii::t('main', 'Production path cannot be save, please contact the administrator.'));
            return $this->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionGetProductionPathSteps() {
        $request = Yii::$app->request;
        $id = $request->get('id');
        $languageId = Language::find()->where(['symbol' => Yii::$app->language])->one()->id;
        $steps = ProductionPathStepQuery::getByProductionPathId($id);
        $productionPath = ProductionPathQuery::getTranslationById($id);

        echo json_encode(['steps' => $steps, 'productionPath' => $productionPath]);
    }

    public function actionGetAttributesForProductionPathSteps($id = null) {

        $productionPathLogic = new ProductionPathLogic();
        $nodeWithAttributes = [];
        $attributes = (new ProductAttributeTypeLogic())->getAttributeGroupsWithTypes();
        if($id != null) {
            $steps = ProductionPathStep::findAll(['production_path_id' => $id]);
            $nodeWithAttributes = [];
            foreach($steps as $step) {
                $stepAttributes = ProductionPathStepAttribute::findAll(['production_path_step_id' => $step['id']]);
                $nodeWithAttributes[$step['id']] = $attributes;
                $forbidden = explode(',', $step->attribute_forbidden_ids);
                $needed = explode(',', $step->attribute_needed_ids);

                foreach($forbidden as $f) {
                    $nodeWithAttributes[$step['id']] = $productionPathLogic->checkAttributs($nodeWithAttributes[$step['id']], $f, 'forbidden', true);
                }

                foreach($needed as $n) {
                    $nodeWithAttributes[$step['id']] = $productionPathLogic->checkAttributs($nodeWithAttributes[$step['id']], $n, 'needed', true);
                }

                foreach($stepAttributes as $stepAttribute) {

public_html/frontend/views/production-path/_path.php
<?php

use yii\helpers\Html;
?>

<div class="row">
    <div id="production-path" class="col-sm-8"></div>
    <div class="col-sm-4">
        <div class="col-sm-12" id="activities-list">
            <?= Html::input('text', 'production-path-name', '', ['id' => 'production-path-name', 'class' => 'form-control', 'placeholder' => Yii::t('main', 'Write production path name')]) ?>
        </div>
        <div class="col-sm-12" id="activities-list">
            <?= Html::input('text', 'activities-search', '', ['id' => 'search-activity', 'class' => 'form-control', 'placeholder' => Yii::t('main', 'Select activity')]) ?>
            <ul id="activities"></ul>
        </div> 
    </div>
</div>
<div class="row product-attribute-container parent-container " id="attributes"></div>
<div class="col-sm-12" id="activities-list">
    <?= Html::button(Yii::t('main', 'Save'), ['class' => 'btn btn-primary pull-right', 'id' => 'saveNetworkButton']) ?>
</div>

public_html/frontend/views/production-path/_productionPaths.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use frontend\models\ProductionPathListForm;
use yii\widgets\LinkPager;
use common\bundles\EnhancedDialogAsset;
use common\widgets\TableHeaderWidget;
use common\helpers\StringHelper;
?>
<?php if(empty($items)) { ?>
    <label><?= Yii::t('web', 'No search results'); ?></label>
    <br><br>				
<?php } else {
    ?>
    <div class="table-responsive">
        <table class="<?= TableHeaderWidget::TABLECLASS ?>">
            <?php echo TableHeaderWidget::widget(['fields' => ProductionPathListForm::getSortFields(), 'listForm' => $listForm]); ?>
            <tbody>
                <?php foreach($items as $item): ?>
                    <tr>
                        <td><?= Html::encode($item['name']) ?></td>
                        <td><?= Html::encode(count(explode(',', $item['topologicalOrder']))) ?></td>
                        <td><?php
                            echo Html::a('', Url::to(['production-path/details', 'id' => $item['id']]), ['class' => 'base-icon details-icon action-icon', 'title' => Yii::t('web', 'Details')]);
                            echo '&nbsp;' . Html::a('', Url::to(['production-path/edit', 'id' => $item['id']]), ['class' => 'base-icon editing-icon action-icon', 'title' => Yii::t('web', 'Edit')]);
                            echo '&nbsp;' . Html::a('', Url::to(['production-path/delete', 'id' => $item['id']]), [
                                    'class' => 'base-icon delete-icon action-icon',
                                    'title' => Yii::t('main', 'Delete'),
                                    'data' => [
                                        'confirm' => Yii::t('main', 'Are you sure you want to delete this item?'),
                                        'method' => 'post',
                                        'params' => [
                                            'id' => $item['id'],
                                        ],
                                    ],
                                ]);
                            ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </div>
    <div class="col-sm-12">
        <div class="col-sm-4 text-left dynamic-table-counter">
            <?= Yii::t('web', 'Number of found items: {n}', ['n' => $pages->totalCount]) ?>
        </div>
        <div class="col-sm-8 text-right dynamic-table-pagination">
            <?= LinkPager::widget(['pagination' => $pages]) ?>
        </div>
    </div>
<?php } ?>

<input class="dynamic-table-sort-dir" type="hidden" name="<?= Html::getInputName($listForm, 'sortDir') ?>" value="<?= $listForm->sortDir ?>" />
<input class="dynamic-table-sort-field" type="hidden" name="<?= Html::getInputName($listForm, 'sortField') ?>" value="<?= $listForm->sortField ?>" />
<input class="dynamic-table-page" type="hidden" name="<?= Html::getInputName($listForm, 'page') ?>" value="<?= $listForm->page ?>" />

<?php
EnhancedDialogAsset::register($this);
?>



public_html/frontend/views/production-path/create.php
<?php

use yii\web\View;
use yii\helpers\Url;


$this->registerJsFile('@web/js/vis-utility.js', ['depends' => [\frontend\assets\AppAsset::className()]]);
$this->registerJsFile('@web/js/pages/production-path.js?'.uniqid(), ['depends' => [\frontend\assets\AppAsset::className()]]);

$this->title = Yii::t('main', 'Create production path') . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'Production'), 'url' => Url::to(['production/index'])];
$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'List of production paths'), 'url' => Url::to(['production-path/list'])];
$this->params['breadcrumbs'][] = Yii::t('main', 'Create production path');


//$this->params['breadcrumbs'][] = Yii::t('web', 'Create production path');
?>

<?= Yii::$app->controller->renderPartial('_path', []); ?>

<?php
$attributePath = Url::to(['production-path/get-attributes-for-production-path-steps']);
$pathStepPath = Url::to(['production-path/get-production-path-steps']);
$activityPath = Url::to(['activity/find']);
$savePath = Url::to(['production-path/save-step-path']);
$this->registerJs('init("' . Yii::$app->language . '", "' . $attributePath . '", "' . $pathStepPath . '", "' . $activityPath . '", "' . $savePath . '");', View::POS_END);
?>

public_html/frontend/views/production-path/details.php
<?php

use yii\web\View;
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\StringHelper;
use common\bundles\EnhancedDialogAsset;

$this->registerJsFile('@web/js/vis-utility.js', ['depends' => [\frontend\assets\AppAsset::className()]]);
$this->registerJsFile('@web/js/pages/production-path.js?' . uniqid(), ['depends' => [\frontend\assets\AppAsset::className()]]);

$this->title = Yii::t('web', 'Production path details') . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'Production'), 'url' => Url::to(['production/index'])];
$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'List of production paths'), 'url' => Url::to(['production-path/list'])];
$this->params['breadcrumbs'][] = Yii::t('web', 'Production path details');
?>

<div class="production-path-details">
    <div class="row">
        <div class="col-sm-6"><h2 class="page-title"><?= StringHelper::translateOrderToOffer('web', 'Production path details') ?></h2></div>
        <div class="col-sm-6 text-right">
            <div>
                <?= Html::a(Yii::t('web', 'Edit'), ['production-path/edit', 'id' => $data['id']], ['class' => 'btn btn-default']) ?>
                <?=
                Html::a(Yii::t('main', 'Delete'), ['production-path/delete', 'id' => $data['id']], [
                    'class' => 'btn btn-default',
                    'data' => [
                        'confirm' => Yii::t('main', 'Are you sure you want to delete this item?'),
                        'method' => 'post',
                    ],
                ])
                ?>
            </div>
        </div>
    </div>

    <div class="col-xs-12 title-with-icon">
        <div class="base-icon basic-data-icon main-content-icons"></div>
        <h3><?= Yii::t('web', 'General information') ?></h3>
    </div>
    <div class="col-xs-12">
        <div class="row">
            <div class=" col-sm-8">
                <div class="table-responsive">
                    <table class="table table-bordered detail-table">
                        <tbody>
                            <tr>
                                <th><?= Yii::t('web', 'Name') ?></th>
                                <td><?= Html::encode($data['name']) ?></td>
                            </tr>
                            <tr>
                                <th><?= Yii::t('web', 'Number of nodes') ?></th>
                                <td><?= Html::encode(count(explode(',', $data['topologicalOrder']))) ?></td>
                            </tr>
                            <?php if($data['isDefault'] == 1) { ?>
                                <tr>
                                    <th><?= Yii::t('web', 'Is default (f)') ?></th>
                                    <td><?= Html::encode(StringHelper::boolTranslation($data['isDefault'], false)) ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 title-with-icon">
        <div class="base-icon gallery-icon main-content-icons"></div>
        <h3><?= Yii::t('web', 'Graph') ?></h3>
    </div>

    <div class="col-xs-12">
        <div id="production-path" class="col-sm-8"></div>
    </div>


    <?php
    EnhancedDialogAsset::register($this);
    ?>
</div>
<?php
$attributePath = Url::to(['production-path/get-attributes-for-production-path-steps']);
$pathStepPath = Url::to(['production-path/get-production-path-steps']);
$activityPath = Url::to(['activity/find']);
$savePath = Url::to(['production-path/save-step-path']);
$this->registerJs('init("' . Yii::$app->language . '", "' . $attributePath . '", "' . $pathStepPath . '", "' . $activityPath . '", "' . $savePath . '", "' . $id . '", "' . $id . '", "' . true . '");', View::POS_END);
?>

public_html/frontend/views/production-path/edit.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->registerJsFile('@web/js/vis-utility.js', ['depends' => [\frontend\assets\AppAsset::className()]]);
$this->registerJsFile('@web/js/pages/production-path.js?' . uniqid(), ['depends' => [\frontend\assets\AppAsset::className()]]);

$this->title = Yii::t('web', 'Edit production path') . ' - ' . Yii::$app->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'Production'), 'url' => Url::to(['production/index'])];
$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'List of production paths'), 'url' => Url::to(['production-path/list'])];
$this->params['breadcrumbs'][] = Yii::t('web', 'Edit production path');
?>

<?= Yii::$app->controller->renderPartial('_path', []); ?>

<?php
$attributePath = Url::to(['production-path/get-attributes-for-production-path-steps']);
$pathStepPath = Url::to(['production-path/get-production-path-steps']);
$activityPath = Url::to(['activity/find']);
$savePath = Url::to(['production-path/save-step-path']);
$this->registerJs('init("' . Yii::$app->language . '", "' . $attributePath . '", "' . $pathStepPath . '", "' . $activityPath . '", "' . $savePath . '", "' . $id . '");', View::POS_END);
?>

public_html/frontend/views/production-path/list.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;

$this->title = Yii::t('web', 'List of production paths') . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'Production'), 'url' => Url::to(['production/index'])];
$this->params['breadcrumbs'][] = Yii::t('web', 'List of production paths');

$this->registerJsFile('@web/js/dynamic-table.js?'.uniqid(), []);
?>

<div id="production-path-list-wrapper">
    <div class="row">
        <div class="col-xs-6"><h2 class="page-title"><?= Yii::t('web', 'List of production paths') ?></h2></div>
        <div class="col-xs-6 text-right">
    		<?= Html::a(Yii::t('main', 'Add production path'), ['production-path/create'], ['class' => 'btn btn-primary']) ?>
        </div>
	</div>

    <div id="production-paths-list-table" class="dynamic-table">
    	<h5><?php echo Yii::t('main','Filters')?></h5>
        <div class="row dynamic-table-filters">
            <div class="col-sm-3">
            	 <label><?= $listForm->getAttributeLabel('name') ?></label>
                    <input 
                        value="<?= $listForm->name ?>" 
                        class="form-control dynamic-table-filter" 
                        type="text"
                        placeholder="<?php echo Yii::t('web','Search by name')?>"
                        name="<?= Html::getInputName($listForm, 'name') ?>">
            </div>
        </div>
        <div class="dynamic-table-data">
            <?= Yii::$app->controller->renderPartial('_productionPaths', [
                'items' => $items,
                'pages' => $pages,
                'listForm' => $listForm,
            ]) ?>
        </div>
    </div>
    <?php 
    	$this->registerJs('dynamicTable("production-paths-list-table", "'.Url::to(['production-path/list']).'");', View::POS_END);
    ?>
</div>