public_html/frontend/controllers/WarehouseProductController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\components\Controller;
use yii\filters\AccessControl;
use common\helpers\Utility;
use yii\data\Pagination;
use yii\helpers\Url;
use common\models\aq\WarehouseQuery;
use frontend\models\WarehouseProductListForm;
use common\models\aq\ProductCategoryQuery;
use common\models\aq\WarehouseProductQuery;
use common\models\ar\Warehouse;
use frontend\models\WarehouseProductForm;
use frontend\models\WarehouseProductItemForm;
use yii\web\Response;
use yii\widgets\ActiveForm;
use common\models\aq\ProductStatusQuery;
use common\models\ar\ProductStatus;
use common\models\aq\ProductStatusReferenceQuery;
use yii\helpers\ArrayHelper;
use common\models\aq\WarehouseProductStatusHistoryQuery;
use common\models\aq\WarehouseProductStatusHistoryDataQuery;
use frontend\models\WarehouseProductDetailsForm;
use frontend\models\ProductReservationListForm;
use common\models\ar\WarehouseProductStatusHistory;
use common\models\ar\ProductStatusReference;
use common\models\ar\WarehouseProduct;
use common\models\ar\WarehouseProductStatusHistoryData;
use yii\filters\VerbFilter;
use common\models\aq\ProductQuery;
use common\alerts\ProductMinimalCountAlertHandler;
use common\models\ar\WarehouseProductOperation;
use common\helpers\NumberTemplateHelper;
use common\documents\DocumentTypeUtility;

class WarehouseProductController extends Controller {

    public function behaviors() {
        $allActions = Yii::$app->params['isWarehouseVisible'] ? ['list', 'details', 'create', 'update', 'get-versions-count-box', 'get-item-form',
            'reservation-list', 'undo-reservation', 'issue-reservation',
                ] : [];

        $rules = !Yii::$app->params['isWarehouseVisible'] ?
                [
                [
                'allow' => false,
                'roles' => ['@'],
            ]
                ] :
                [
                [
                'actions' => ['list', 'details', 'create', 'update', 'get-versions-count-box', 'get-item-form',
                    'reservation-list', 'issue-reservation',],
                'allow' => true,
                'roles' => [Utility::ROLE_STOREKEEPER],
            ],
                [
                'actions' => ['undo-reservation'],
                'allow' => true,
                'roles' => [Utility::ROLE_SALESMAN, Utility::ROLE_STOREKEEPER],
            ]
        ];

        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => $allActions,
                'rules' => $rules,
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'undo-reservation' => ['post'],
                    'issue-reservation' => ['post'],
                ],
            ],
        ];
    }

    public function actionList() {
        $request = Yii::$app->request;
        $listForm = new WarehouseProductListForm();
        if(!$request->isAjax) {
            $categoryOptions = ProductCategoryQuery::getCategoryList();
            $listForm->allCategoriesCount = count($categoryOptions);

            $warehouseOptions = WarehouseQuery::getWarehouseList()->all();
            $listForm->allWarehousesCount = count($warehouseOptions);
        }
        $listForm->load($request->get());

        $itemsQuery = WarehouseProductQuery::getActiveProductsQuery($listForm->toArray());
        $pages = new Pagination([
            'totalCount' => $itemsQuery->count(),
            'page' => $listForm->page,
            'defaultPageSize' => \Yii::$app->params['defaultPageSize'],
        ]);
        $items = $itemsQuery->limit($pages->defaultPageSize)->offset($pages->page * $pages->defaultPageSize)->all();

        $listData = [
            'items' => $items,
            'pages' => $pages,
            'listForm' => $listForm,
        ];

        if($request->isAjax) {
            echo json_encode([
                'view' => $this->renderAjax('_products', $listData),
                'url' => Url::current([], true),
            ]);
        } else {
            $listData['categoryTranslations'] = $categoryOptions;
            $listData['warehouses'] = $warehouseOptions;
            return $this->render('list', $listData);
        }
    }

    public function actionDetails($productId) {
        $request = Yii::$app->request;
        $productDetails = WarehouseProductQuery::getActiveProductsQuery(['productId' => $productId])->limit(1)->one();
        if(empty($productDetails)) {
            throw new \yii\web\NotFoundHttpException(Yii::t('web', 'Element does not exist or you do not have permission.'));
        }
        $detailsForm = new WarehouseProductDetailsForm();
        if(!$request->isAjax) {
            $warehouseOptions = WarehouseQuery::getWarehouseList()->all();
            $detailsForm->allWarehousesCount = count($warehouseOptions);
        }
        $detailsForm->load($request->get());

        $itemsQuery = WarehouseProductStatusHistoryQuery::getStatusesQueryByProductId($productId, $detailsForm->toArray());
        $pages = new Pagination([
            'totalCount' => $itemsQuery->count(),
            'page' => $detailsForm->page,
            'defaultPageSize' => \Yii::$app->params['defaultPageSize'],
        ]);
        $items = $itemsQuery->limit($pages->defaultPageSize)->offset($pages->page * $pages->defaultPageSize)->all();
        $subversions = WarehouseProductQuery::getAllProductSubversionsInWarehouses($productId);

        $subversionsDim[] = count($subversions);
        if(count($subversions) != 0) {
            $subversionsDim[] = count($subversions[0]);
        }

        if(!empty($items)) {
            foreach($items as &$item) {
                if($item['countAdditionalData'] > 0) {
                    $item['additionalData'] = WarehouseProductStatusHistoryDataQuery::getDataByHistoryId($item['id']);
                }
            }
        }

        $listData = [
            	'items' => $items,
            	'pages' => $pages,
            	'listForm' => $detailsForm,
            	'productId' => $productId,
            	'subversions' => $subversions,
            	'subversionsDim' => $subversionsDim,
        		'availableDocuments' => DocumentTypeUtility::getAvailableDocuments(),
        ];

        if($request->isAjax) {
            echo json_encode([
                'view' => $this->renderAjax('_statuses', $listData),
                'url' => Url::current([], true),
            ]);
        } else {
            if(!empty($productId)) {
                $productDetails['attachments'] = ProductQuery::getAttachments($productId);
            }

            $listData['warehouses'] = $warehouseOptions;
            $listData['productDetails'] = $productDetails;

            return $this->render('details', $listData);
        }
    }

    public function actionCreate($productId = null) {
        $model = new WarehouseProductForm();
        $model->setAddScenario();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $errors = ActiveForm::validate($model) + ActiveForm::validateMultiple($model->warehouseProductItemForms);
            return $model->translateErrorMessages($errors);
        }

        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            try {
                $model->saveData();
                Yii::$app->getSession()->setFlash('success', Yii::t('web', 'Products has been added successfully to warehouse.'));

                return $this->redirect(['list']);
            } catch(\Exception $e) {
                Yii::$app->getSession()->setFlash('error', Yii::t('web', 'Products cannot be added to warehouse. Check provided values.'));
                Yii::error($e->getMessage());
                Yii::error($e->getTraceAsString());
            }
        }

        return $this->render('form', [
                    'model' => $model,
                    'product' => empty($productId) ? null : new WarehouseProductItemForm($productId),
        ]);
    }

    public function actionUpdate($productId = null, $productStatusId = null) {
        $model = new WarehouseProductForm();
        $model->setUpdateScenario();

        if(Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $errors = ActiveForm::validate($model) + ActiveForm::validateMultiple($model->warehouseProductItemForms);
            return $model->translateErrorMessages($errors);
        }

        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            try {
                $model->saveData();
                Yii::$app->getSession()->setFlash('success', Yii::t('web', 'Products in warehouse have been updated successfully.'));

                return $this->redirect(['list']);
            } catch(\Exception $e) {
                Yii::$app->getSession()->setFlash('error', Yii::t('web', 'Products in warehouse cannot be updated. Check provided values.'));
                Yii::error($e->getMessage());
                Yii::error($e->getTraceAsString());
            }
        }

        $operationTypes = ProductStatusQuery::getStatusesByNotSymbols([Utility::PRODUCT_STATUS_ADDITION, Utility::PRODUCT_STATUS_UNDO_RESERVATION, Utility::PRODUCT_STATUS_ISSUING_RESERVATION]);
        $fields = ProductStatusReferenceQuery::getAdditionalFieldsByProductStatusIds(ArrayHelper::getColumn($operationTypes, 'id'));
        if(!empty($fields)) {
            $model->setAdditionalFields($fields);
        }

        $model->productStatusId = $productStatusId;


public_html/frontend/views/warehouse-product/_products.php
<?php 
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use common\bundles\EnhancedDialogAsset;
use frontend\models\WarehouseProductListForm;
use yii\web\View;
use common\helpers\StringHelper;
use common\widgets\TableHeaderWidget;
?>

<?php
if (empty($items)) { ?>
	<label><?= Yii::t('web', 'No search results');?></label>
	<br><br>
<?php }
else { ?>
	<div class="table-responsive">
		<table class="<?= TableHeaderWidget::TABLECLASS ?>">
	    	<?php echo TableHeaderWidget::widget(['fields' => WarehouseProductListForm::getSortFields(), 'listForm' => $listForm]);?>

	        <tbody>
	            <?php foreach($items as $item): ?>
	                <tr>
                        <?php if(Yii::$app->params['isProductPhotoOnListVisible']){ ?>
                            <td><span class="photo-container">
                                <?= '<div class="photo-medium" style="background: url('.(!empty($item['urlPhoto']) ? \common\helpers\UploadHelper::getNormalPath($item['urlPhoto'], 'product_photo') : Url::to('@web/images/placeholders/product.png')).')"></div>'; ?>
                                <?php if(!empty($item['urlPhoto'])) { ?>
                                    <div class="photo-tooltip" data-id="<?= $item['productId'] ?>"></div>
                                <?php } ?>
                            </span></td>
                        <?php } ?>

	                    <td><?= Html::encode($item['name']) ?></td>
	                    	                   	<td><?php if(!empty($item['stillage']) && !empty($item['shelf'])) {
	                   		echo !empty($item['stillage']) ? Html::encode($item['stillage']) : '-';
	                   		echo '/';
	    	                echo !empty($item['shelf']) ? Html::encode($item['shelf']) : '-';
	                   	}
	                   	else {
	                   		Html::encode($item['stillage']);
	                   	}
	                   	 ?></td>
	                    <td><?= Html::encode($item['supplier']) ?></td>
	                    <td><?= Html::encode($item['category']) ?></td>
	                    <td class="count-cell"><?php
	                    	echo $item['countAvailableSum']
	                    			.(!empty($item['unit']) ? ' '.$item['unit'] : '')
	                    			.(!empty($item['countMinimal']) ? ' ('.$item['countMinimal'].')' : '');
	                    	if(!empty($item['versionCount'])) {
	                    		echo ' <span class="button-show-versions glyphicon glyphicon-menu-down pull-right" data-id="'.$item['productId'].'"></span>';
	                    		echo '<div class="versions-details" style="display: none"></div>';
	                    	}
	                    ?></td>
	                    <td>
                            <?php if($item['currencyShortSymbol'] && ($item['priceUnit'] || $item['priceGroup'])): ?>
                                <?php $price = ($item['priceUnit'] === null) ? $item['priceGroup'] : $item['priceUnit'] ?>
                                <?= StringHelper::getFormattedCost($price).' '.$item['currencyShortSymbol']
                                        .'/'
                                        .mb_strtolower(Yii::t('web', ($item['priceUnit'] === null) ? 'Package': 'Unit'), 'utf-8') 
                                ?>
                            <?php endif ?>
	                    </td>           
	                    <td><?= Html::encode(StringHelper::getFormattedDateFromTimestamp($item['dateModification'], true)) ?></td>
	                    <td><?php
	                    	echo Html::a('', Url::to(['warehouse-product/details', 'productId' => $item['productId']]), ['class' => 'base-icon details-icon action-icon', 'title' => Yii::t('web', 'Details')]);
	                    	
	                    	$confirmMessage = Yii::t('main', 'Are you sure you want to delete this item?');
	                    	if($item['countSum'] > 0) {
	                    		$confirmMessage .= '<br/><strong>' . Yii::t('main', 'If you confirm, all products of this kind will be deleted from warehouses!') . '</strong>';
	                    	}
	                    	echo '&nbsp;'.Html::a('', Url::to(['product/delete']), [
	                    			'class' => 'base-icon delete-icon action-icon',
                                    'title' => Yii::t('main', 'Delete'),
	                    			'data' => [
	                    					'confirm' => $confirmMessage,
	                    					'method' => 'post',
	                    					'params' => [
	                    							'id' => $item['productId'],
	                    					],
	                    			],
	                    	]);
	                    ?></td>
	                </tr>
	            <?php endforeach ?>
	        </tbody>
	    </table>
	</div>
	<div class="col-sm-12">
		<div class="col-sm-4 text-left dynamic-table-counter">
			<?= Yii::t('web', 'Number of found items: {n}', ['n' => $pages->totalCount]) ?>
		</div>
		<div class="col-sm-8 text-right dynamic-table-pagination">
		    <?= LinkPager::widget(['pagination' => $pages ]) ?>
		</div>
	</div>
<?php }?>

<input class="dynamic-table-sort-dir" type="hidden" name="<?= Html::getInputName($listForm, 'sortDir') ?>" value="<?= $listForm->sortDir ?>" />
<input class="dynamic-table-sort-field" type="hidden" name="<?= Html::getInputName($listForm, 'sortField') ?>" value="<?= $listForm->sortField ?>" />
<input class="dynamic-table-page" type="hidden" name="<?= Html::getInputName($listForm, 'page') ?>" value="<?= $listForm->page ?>" />

<?php 
	$this->registerJs('initDynamicFeatures();', View::POS_END); 
	EnhancedDialogAsset::register($this);	
?>

public_html/frontend/views/warehouse-product/_reservedProducts.php
<?php 
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use common\bundles\EnhancedDialogAsset;
use frontend\models\ProductReservationListForm;
use yii\web\View;
use common\helpers\StringHelper;
use frontend\helpers\AdditionalFieldHelper;
use common\models\ar\TaskType;
use common\helpers\Utility;
use common\widgets\TableHeaderWidget;
?>

<?php 
if (empty($items)) { ?>
	<label><?= Yii::t('web', 'No search results');?></label>
	<br><br>					
<?php }
else { ?>
	<div class="table-responsive">
	    <table class="<?= TableHeaderWidget::TABLECLASS ?>">
	        <?php echo TableHeaderWidget::widget(['fields' => ProductReservationListForm::getSortFields(), 'listForm' => $listForm, 'iconCount' => 4]);?>
	        <tbody>
	            <?php 
	            	$taskTypeId = TaskType::find()->where(['symbol' => Utility::TASK_TYPE_ORDER_PRODUCT])->one()->id;	
	            
	            	foreach($items as $item): ?>
	                <tr>
	                    <td><?= Html::encode($item['title']) ?></td>
	                    <td><?= Html::encode($item['name']) ?></td>   
	                    <td><?= Html::encode($item['count']) ?></td>
	                    <td><?= Html::encode(StringHelper::getFormattedDateFromDate($item['date_creation'], true)) ?></td>
	                    <td><?= Html::encode(AdditionalFieldHelper::getFormattedData([['table' => 'user', 'name' => $item['user']]], true)) ?></td>
	                    
	                    <td><?php 
	                    	echo Html::a('', Url::to(['warehouse-product/details', 'productId' => $item['productId']]), ['class' => 'base-icon details-icon action-icon', 'title' => Yii::t('web', 'Details')])
	                    			.'&nbsp;'.Html::a('', Url::to(['task/create', 
			                    					'productId' => $item['productId'], 
			                    					'userNotifiedId' => $item['userConfirmingId'],
	                    							'taskTypeId' => $taskTypeId,
			                    			]), [
                                                'class' => 'base-icon reservation-icon action-icon', 
                                                'target' => '_blank',
                                                'title' => Yii::t('web', 'Create reservation task'),
                                                ])

	                    			.'&nbsp;'.Html::a('', ['warehouse-product/undo-reservation'], [
	                    							'class' => 'base-icon cancel-icon action-icon',
                                                    'title' => Yii::t('web', 'Undo reservation'),
	                    							'data' => [
	                    									'confirm' => Yii::t('web', 'Are you sure you want to undo this reservation?'),
	                    									'method' => 'post',
	                    									'params' => [
	                    											'operationId' => $item['id'],
	                    											'orderId' => $item['orderId'],
	                    									],
	                    							],
	                    					])
                    				.'&nbsp;'.Html::a('', ['warehouse-product/issue-reservation'], [
                    								'class' => 'base-icon issue-icon action-icon',
                                                    'title' => Yii::t('web', 'Issue product related to reservation'),
                    								'data' => [
                    										'confirm' => Yii::t('web', 'Are you sure you want to issue products related to this reservation?'),
                    										'method' => 'post',
                    										'params' => [
                    												'operationId' => $item['id'],
                    												'orderId' => $item['orderId'],
                    										],
                    								],
                    						]);
	                    ?></td>
	                </tr>
	            <?php endforeach ?>
	        </tbody>
	    </table>
	</div>
	<div class="col-sm-12">
		<div class="col-sm-4 text-left dynamic-table-counter">
			<?= Yii::t('web', 'Number of found items: {n}', ['n' => $pages->totalCount]) ?>
		</div>
		<div class="col-sm-8 text-right dynamic-table-pagination">
		    <?= LinkPager::widget(['pagination' => $pages ]) ?>
		</div>
	</div>
<?php }?>

<input class="dynamic-table-sort-dir" type="hidden" name="<?= Html::getInputName($listForm, 'sortDir') ?>" value="<?= $listForm->sortDir ?>" />
<input class="dynamic-table-sort-field" type="hidden" name="<?= Html::getInputName($listForm, 'sortField') ?>" value="<?= $listForm->sortField ?>" />
<input class="dynamic-table-page" type="hidden" name="<?= Html::getInputName($listForm, 'page') ?>" value="<?= $listForm->page ?>" />

<?php EnhancedDialogAsset::register($this); ?>

public_html/frontend/views/warehouse-product/form.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;
use yii\helpers\ArrayHelper;
use kartik\widgets\Select2;
use yii\web\JsExpression;
use common\models\aq\WarehouseQuery;
use frontend\helpers\AdditionalFieldHelper;

$this->registerCssFile('@web/css/select2.min.css');
$this->registerCssFile('@web/css/select2-bootstrap.min.css');
$this->registerJsFile('@web/js/select2/select2.min.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);
$this->registerJsFile('@web/js/select2/i18n/'.Yii::$app->language.'.js?'.uniqid(), ['depends' => [\yii\web\JqueryAsset::className()]]);

$subtitle = $model->isUpdateScenarioSet() ? Yii::t('web', 'Update products in warehouse') : Yii::t('web', 'Add products to warehouse');
$this->title = $subtitle.' - '.Yii::$app->name;

$this->params['breadcrumbs'][] = ['label' => Yii::t('main', 'Warehouse'), 'url' => Url::to(['warehouse/index'])];
$this->params['breadcrumbs'][] = ['label' => Yii::t('web', 'Current products in warehouse'), 'url' => Url::to(['warehouse-product/list'])];
$this->params['breadcrumbs'][] = $subtitle;
?>

<div class="warehouse-product-form">
		
	<div class="row">
		<div class="col-sm-8 col-xs-12"><h2 class="page-title"><?= $subtitle ?></h2></div>
		<div class="col-sm-4 col-xs-12 text-right"><?= Html::a(Yii::t('web', 'Add warehouse product'), ['product/create'], ['class' => 'btn btn-primary', 'target' => '_blank']) ?>
		</div>
	</div>

	<?php $form = ActiveForm::begin([
			'id' => 'warehouse-product-form',
			'enableAjaxValidation' => true,
	]); ?>
					
	<div class="row">
		<div class="col-sm-6"><?php
			echo $form->field($model, 'warehouseId', ['options' => ['style' => 'display: '.(Yii::$app->params['isMoreWarehousesAvailable'] ? 'block' : 'none')]])->dropDownList(ArrayHelper::map(WarehouseQuery::getWarehouseList()->all(), 'id', 'name'));
		?></div>
	</div>

    <div id="delivery-products" class="items-container">
    <?php 
        if(!empty($product)) {
            echo $this->renderAjax('inc/_item', [
                            'warehouseProductItemForm' => $product,
                            'prefix' => 0,
                            'formId' => 'warehouse-product-form',
                    ]); 
        }
    ?>
    </div>
    <div class="product-select col-sm-12">
    	<div class="row">
            <div class="col-sm-6">
            <h4><?= Yii::t('web', 'Add product') ?></h4>
            
                <?= Select2::widget([
                        'id' => 'select2-search-product',
                        'name' => 'select2-search-product',
                        'language' => Yii::$app->language,
                        'options' => ['placeholder' => Yii::t('web', 'Select a product...')],
                        'data' => null,
                        'pluginOptions' => [
                                'allowClear' => true,
                                'minimumInputLength' => 1,
                                'ajax' => [
                                        'url' => Url::to(['product/find']),
                                        'dataType' => 'json',
                                        'delay' => 250,
                                        'data' => new JsExpression('function(params) { return { term:params.term, page:params.page, size: 20 }; }'),
                                        'processResults' => new JsExpression('function (data, params) {
                                            params.page = params.page || 1;
    
                                            return {
                                                results: data.items,
                                                pagination: {
                                                    more: data.more
                                                }
                                            };
                                        }'),
                                        'cache' => true
                                ],
                                'templateResult' => new JsExpression('function(item) { if(item.loading) return item.text; return item.name; }'),
                                'templateSelection' => new JsExpression('function (item) { return item.name || item.text; }'),
                        ],
                        'pluginEvents' => [
                                'select2:selecting' => 'function(e) {
                                    var productId = e.params.args.data.id;
                                    var fetchProduct = function() {
                                        window.wpiCurrentPrefix = window.wpiCurrentPrefix || 1;
                                        
                                        $.ajax({
                                            method: "GET",
                                            url: "'.Url::to(['warehouse-product/get-item-form']).'",
                                            data: { 
                                                productId: productId,
                                                prefix: window.wpiCurrentPrefix++,
                                                formId: "warehouse-product-form"
                                            },									
                                            async: false
                                        }).done(function(data) {
                                            var $product = $(data);
                                            $("#delivery-products").append($product);
                                            $product.find(".remove-item-btn:first").on("click", function() {
                        						$product.remove();
                                            })
                                        });	
                                    }
                                    
                                    var selectedProductsIds = {};
                                    $("#delivery-products .product-id").each(function(idx, idField) {
                                        selectedProductsIds[idField.value] = idField.value
                                    });
    
                                    if(selectedProductsIds[productId] === undefined) {
                                        fetchProduct();
                                    }
                                }',	
                        ],
                    ]); 
                ?>
    
                <?php
                    $this->registerJs('
                        (function() {
                            var $addProductSelect = $("#select2-search-product");
                            $addProductSelect.on("change", function() {
                                $addProductSelect.val("");
                            });
                        })();
                ', View::POS_END); 
                ?>
                <a href="<?= Url::to(['product/create']); ?>" target="_blank" class="focusable-link  add-item-after-select2 add-item-after-select2-no-required">
                    <span class="glyphicon glyphicon-plus-sign pull-left"></span>
                    <span> <?=Yii::t('web', 'Create new product')?></span>
                </a>
            </div>
		</div>
    </div>
    

		<div class="col-sm-10">
			<h4><?= Yii::t('web', 'Comment') ?></h4>
			<?php 
				echo $form->field($model, 'description')->textarea(['maxlength' => true, 'placeHolder' => $model->getAttributeLabel('description'),])->label(false);
			?>
		</div>

	
	<?php if($model->isUpdateScenarioSet()) { ?>
	<div class="col-sm-12">
		<h4><?= Yii::t('web', 'Select operations') ?></h4>
			<div class="col-lg-8 col-lg-offset-2 col-xs-12">
				<?= $form->field($model, 'productStatusId')->hiddenInput()->label(false); ?>
				<div class="btn-group buttons-operation-types" role="group" aria-label="...">
					<?php foreach($operationTypes as $operationType) { ?>
						<button type="button" class="btn btn-primary button-operation-type <?= $model->productStatusId == $operationType['id'] ? 'buttonClick' : '' ?>" 
								data-id="<?= $operationType['id'] ?>"><?= $operationType['name'] ?></button>
					<?php } ?>
				</div>
			</div>
		</div>
		
		<div class="col-sm-12">
			<div class="row">
    			<div class="col-sm-6 col-sm-offset-3 col-xs-12" id="additional-fields-container">
    				<?php echo AdditionalFieldHelper::renderAdditionalFields($model, $form, $fields, 'productStatusId'); ?>
    			</div>
			</div>
		</div>
	<?php } ?>

	<div class="col-sm-12">
		<div class="pull-left"><?= Html::a(Yii::t('web', 'Cancel'), ['warehouse-product/list'], ['class' => 'btn btn-default']) ?></div>
		<div class="pull-right"><?= Html::submitButton(($model->isUpdateScenarioSet() ? Yii::t('web', 'Execute') : Yii::t('web', 'Add')), ['class' => 'btn btn-primary']); ?></div>
	</div>
	
	<?php ActiveForm::end(); ?>	
</div>

<?php 
	if($model->isUpdateScenarioSet()) {
		$this->registerJs('
					$("#warehouseproductform-productstatusid").on("change", function(e) {
						console.log("Wchodzi");
						var productStatusId = $("#warehouseproductform-productstatusid").val();
						var fields = '.json_encode($fields).';
				
						$.each(fields, function(i, v) {
							var componentSelect2 = $("#select2-" + v.productStatusId + "-" + v.id + "-" + v.symbol);
							componentSelect2.css("display", "none");
							var componentTextInput = $("#text-input-" + v.productStatusId + "-" + v.id + "-" + v.symbol);
							componentTextInput.css("display", "none");
				
						    if(v.productStatusId == productStatusId) {
						        componentSelect2.css("display", "block");
								componentTextInput.css("display", "block");
						    }
						});
					}).trigger("change");
				
					$(".button-operation-type").click(function(e) {
						console.log("Wchodzi2");
						var productStatusId = $(this).data("id");
						$("#warehouseproductform-productstatusid").val(productStatusId).trigger("change");
					});
				', View::POS_END);
	}
?>